### PR TITLE
monitoring: added more description strings about backend defrag state

### PR DESCRIPTION
**Pull request by abudnik**
subj

### CODE REVIEW

**Comment by bioothod** [comment]
Looks like patch is not completed - none sets those new flags

**Comment by abudnik** [comment]
>none sets those new flag
Flags from dnet_backend_defrag_state matches to those in eblob_defrag_state. Nothing has changed in this patch, except that more flags were added.

**Comment by bioothod** [comment]
What is 'compact is in progress', there is no such state in eblob?

**Comment by abudnik** [comment]
Also this PR connected with appropriate PR in eblob: https://github.com/reverbrain/eblob/pull/108

**Comment by bioothod** [comment]
Ok, I see.
I suppose this pull request will be extended according to eblob pull request discussion?

**Comment by abudnik** [comment]
>I suppose this pull request will be extended according to eblob pull request discussion?

Yes

**Pull request closed without merging**
