### PR TITLE
Check that backend supports iterator before run it.

### PR DESCRIPTION
**Pull request by shaitan**

### CODE REVIEW

**Comment by bioothod** [comment]
Should it write error message to log in this case?

**Comment by shaitan** [comment]
It will write error message right after `error_out_exit` label but with `DNET_LOG_NOTICE`. I can change the log level of the message in case of error.

**Comment by bioothod** [comment]
But it will not tell us why -95 is returned, i.e. exactly who is responsible for this error

**Comment by shaitan** [comment]
Added additional logs at iteration failures

**Pull request merged**
